image: docker:latest

stages:
  - build
  - test
  - stage
  - production

variables:
  MONGO: mongodb
  MONGO_PORT: 27017
  RMQ_HOST: rmq
  RMQ_QUEUE: urls
  DOCKER_DRIVER: overlay2

build_app:
  stage: build
  services:
    - docker:dind
  script:
    - echo 'Building'
    - docker build -t $DOCKER_REGISTRY_USER/crawler-app:latest .
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
    - docker push $DOCKER_REGISTRY_USER/crawler-app:latest && docker image rm $DOCKER_REGISTRY_USER/crawler-app:latest

test_app:
  stage: test
  services:
    - docker:dind
  script:
    - echo 'Test'
    - docker run $DOCKER_REGISTRY_USER/crawler-app:latest python -m unittest discover -s tests/

staging_app:
  stage: stage
  script:
    - echo 'Publish to stage'
    - apk update && apk add openssh
    - >
      ssh -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no $DEPLOY_USER@$STAGE_VM
      "docker stop crawler-app || true &&
      docker run -d --rm --name crawler-app --network=test -e MONGO=$MONGO -e MONGO_PORT=$MONGO_PORT
      -e RMQ_HOST=$RMQ_HOST -e RMQ_QUEUE=$RMQ_QUEUE -e RMQ_USERNAME=$RMQ_USERNAME -e RMQ_PASSWORD=$RMQ_PASSWORD
      $DOCKER_REGISTRY_USER/crawler-app:latest"
  environment: 
    name: stage
    url: http://$STAGE_VM:8000

production_app:
  stage: production
  when: manual
  script:
    - echo 'Publish to prod'
    - apk update && apk add openssh
    - >
      ssh -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no $DEPLOY_USER@$PROD_VM
      "docker stop crawler-app || true &&
      docker run -d --rm --name crawler-app --network=test -e MONGO=$MONGO -e MONGO_PORT=$MONGO_PORT
      -e RMQ_HOST=$RMQ_HOST -e RMQ_QUEUE=$RMQ_QUEUE -e RMQ_USERNAME=$RMQ_USERNAME -e RMQ_PASSWORD=$RMQ_PASSWORD
      $DOCKER_REGISTRY_USER/crawler-app:latest"
  only:
    - master
  environment:
    name: production
    url: http://$PROD_VM:8000
